import type { Metadata } from "next";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.css";
import BootstrapJs from "@/utils/bootstrap-js/BootstrapJs";
import NavBar from "./components/NavBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/* <div className="p-5 m-2 position-sticky top-0 w-100"><NavBar /></div> */}
        <div>{children}</div>
        </body>
      <BootstrapJs />
    </html>
  );
}
