import type { Metadata } from "next";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.css";
import BootstrapJs from "@/utils/bootstrap-js/BootstrapJs";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let camelcase = "hello";
  return (
    <html lang="en">
      <body>
        <div>{children}</div>
        </body>
      <BootstrapJs />
      {camelcase}
    </html>
  );
}
